In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
# range version fro numpy (start, end, step)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [6]:
# generate array of zeros of n rows and m columns (shape=(n, m))
np.zeros(shape=(4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Generate arrays with a given seed (this seed is for generating same random values)
np.random.seed(101)
arr = np.random.randint(0, 100, 10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [9]:
arr2 = np.random.randint(0, 100, 10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [10]:
# Max value of array
arr.max()

95

In [11]:
# Index of max value
arr.argmax()

0

In [12]:
# Min value
arr.min()

9

In [13]:
# Index of min value
arr.argmin()

7

In [14]:
# Mean of the whole array
arr.mean()

60.8

In [15]:
# It's possible to reshape an array, just considering the dimensions make sense
arr.reshape((5, 2))

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [18]:
# Generate array and reshape
mat = np.arange(0, 100).reshape((10, 10))

In [19]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
mat.shape

(10, 10)

In [21]:
# Indexing
row = 3
col = 5
mat[row, col]

35

In [22]:
# Return every row of a specific column
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [23]:
mat[:,5].reshape((10,1))

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [24]:
# Create a copy of a matrix
mynewmat = mat.copy()

In [25]:
mynewmat[0:6,:] = 999
mynewmat

array([[999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])